#!/usr/bin/env python3
"""Write Wave 4 aquarium venue JSONs + catalog.js kits (2026-08-23 official pass).

Does not rewrite card-kinds.tsv. Does not touch Wave 1–3 zoo / safari_zoo kits.
Does not edit omaha-henry-doorly, pittsburgh-zoo, or point-defiance-zoo.
Does not touch museums or parks. No new cards.
Aquarium kits list kind aquarium|both only.
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from write_wave3a_venues import META, TITLES  # noqa: E402
from write_wave3a_venues import apply_kit as _apply_kit  # noqa: E402
from write_wave3a_venues import ban, item, patch_venue  # noqa: E402

TITLES.update({
    "clownfish": "Clownfish",
    "crab": "Crab",
    "eel": "Eel",
    "jellyfish": "Jellyfish",
    "octopus": "Octopus",
    "starfish": "Sea star",
    "sea-turtle": "Sea turtle",
    "seahorse": "Seahorse",
    "stingray": "Stingray",
    "puffin": "Puffin",
    "sea-otter": "Sea otter",
    "manta-ray": "Manta ray",
    "kelp-forest": "Kelp forest",
    "cuttlefish": "Cuttlefish",
    "whale-shark": "Whale shark",
})

META.update({
    "clownfish": ("🐠", ["water", "color"], "Bright reef fish — friends with anemones."),
    "crab": ("🦀", ["water", "shell"], "Sideways walker with a hard shell."),
    "eel": ("🐍", ["water", "hide"], "Long snaky fish — loves rocky hidey-holes."),
    "jellyfish": ("🎐", ["water", "glow", "soft"], "Soft drifter — watch them pulse."),
    "octopus": ("🐙", ["water", "hide", "smart"], "Eight arms — check the corners."),
    "starfish": ("⭐", ["water", "touch"], "Star-shaped ocean friend."),
    "sea-turtle": ("🐢", ["water", "shell"], "Shelled ocean traveler — flippers, not feet."),
    "seahorse": ("🌊", ["water", "tiny"], "Tiny upright swimmer that holds on with its tail."),
    "stingray": ("🐟", ["water", "flat", "touch"], "Flat swimmer — gentle hands if a pool is open."),
    "puffin": ("🐦", ["birds", "water"], "Seabird that flies, swims, and carries a beak of fish."),
    "sea-otter": ("🦦", ["water", "play", "wow"], "Furriest swimmer — floats on its back."),
    "manta-ray": ("🐟", ["water", "big", "wow"], "Giant winged swimmer — bigger and gentler than a stingray."),
    "kelp-forest": ("🌿", ["water", "hide"], "An underwater forest of giant seaweed."),
    "cuttlefish": ("🦑", ["water", "hide"], "Color-changing cousin of the octopus."),
    "whale-shark": ("🦈", ["water", "big", "wow"], "Biggest fish in the sea — a gentle giant."),
})


def apply_kit(slug: str, *, official_url: str | None = None, **kwargs) -> None:
    _apply_kit(slug, **kwargs)
    if official_url:
        patch_venue(slug, official_url=official_url)


ZOO_ONLY_BANS = [
    "african-elephant",
    "african-lion",
    "sumatran-tiger",
    "western-lowland-gorilla",
    "chimpanzee",
    "reticulated-giraffe",
    "zebra",
    "red-panda",
    "nile-hippo",
    "galapagos-tortoise",
    "orangutan",
    "cheetah",
    "koala",
    "giant-panda",
    "ring-tailed-lemur",
    "cm-outdoor",
]


def bans_except(keep: set[str], extra: list[tuple[str, str]] | None = None) -> list[dict]:
    reasons = {
        "african-elephant": "Zoo-only card — aquarium kits list aquarium|both only.",
        "african-lion": "Zoo-only card — aquarium kits list aquarium|both only.",
        "sumatran-tiger": "Zoo-only card — aquarium kits list aquarium|both only.",
        "western-lowland-gorilla": "Zoo-only card — aquarium kits list aquarium|both only.",
        "chimpanzee": "Zoo-only card — aquarium kits list aquarium|both only.",
        "reticulated-giraffe": "Zoo-only card — aquarium kits list aquarium|both only.",
        "zebra": "Zoo-only card — aquarium kits list aquarium|both only.",
        "red-panda": "Zoo-only card — aquarium kits list aquarium|both only.",
        "nile-hippo": "Zoo-only card — aquarium kits list aquarium|both only.",
        "galapagos-tortoise": "Zoo-only card — aquarium kits list aquarium|both only.",
        "orangutan": "Zoo-only card — aquarium kits list aquarium|both only.",
        "cheetah": "Zoo-only card — aquarium kits list aquarium|both only.",
        "koala": "Zoo-only card — aquarium kits list aquarium|both only.",
        "giant-panda": "Zoo-only card — aquarium kits list aquarium|both only.",
        "ring-tailed-lemur": "Zoo-only card — drop even if an official rainforest list names a lemur.",
        "cm-outdoor": "Neither-kind leftover — aquarium kits list aquarium|both only.",
    }
    out = [ban(cid, reasons[cid]) for cid in ZOO_ONLY_BANS if cid not in keep]
    for cid, reason in extra or []:
        if cid not in {row["catalog_id"] for row in out}:
            out.append(ban(cid, reason))
    return out


def main() -> None:
    apply_kit(
        "aquarium-of-the-pacific",
        verified=True,
        tagline="Southern sea otters and tufted puffins first, then Shark Lagoon — Magellanic penguins, not African.",
        items=[
            item("sea-otter", zone="Sea Otter Habitat", one="Southern sea otter — floats, snacks, and steals the show.", core=True),
            item("puffin", zone="Diving Birds", one="Tufted puffin — a beak full of fish.", core=True, note="Official Northern Pacific / Diving Birds: tufted puffin."),
            item("shark", zone="Shark Lagoon", one="Shark Lagoon — zebra, reef, and bamboo sharks.", core=True),
            item("stingray", zone="Shark Lagoon", one="Rays share Shark Lagoon and the Tropical Reef.", core=True),
            item("jellyfish", zone="Jelly Dreamscapes", one="Jelly Dreamscapes — slow down and watch them pulse.", core=True),
            item("sea-turtle", zone="Tropical Pacific", one="Olive Ridley sea turtle in the Tropical Reef.", core=True),
            item("octopus", zone="Northern Pacific", one="Giant Pacific octopus — check the corners.", core=False),
            item("clownfish", zone="Tropical Pacific", one="Clownfish darting through the Tropical Reef.", core=False),
            item("eel", zone="Southern California / Tropical", one="Moray eel — a long stare from a rocky hole.", core=False),
            item("kelp-forest", zone="Southern California Gallery", one="Casino Point kelp forest — an underwater forest.", core=False),
        ],
        bans=bans_except(set(), [
            ("african-penguin", "Official June Keyes Penguin Habitat is Magellanic penguin."),
            ("asian-small-clawed-otter", "Official otter is southern sea otter."),
            ("seahorse", "Not named on official exhibit pages reviewed."),
            ("starfish", "Stars of the Sea not confirmed as a current exhibit."),
        ]),
        sources=[
            "https://www.aquariumofpacific.org/exhibits/",
            "https://www.aquariumofpacific.org/exhibits/otters",
            "https://www.aquariumofpacific.org/exhibits/penguin_habitat",
            "https://www.aquariumofpacific.org/exhibits/shark_lagoon",
            "https://www.aquariumofpacific.org/exhibits/jellydreamscapes",
        ],
        notes="[2026-08-23] Official-source Wave 4 public list pass (aquariumofpacific.org exhibits). Magellanic penguin ≠ African.",
        hunt_tag="Pacific bonus · sea otter + puffin + Shark Lagoon",
        hunt_finds=["stingray", "jellyfish", "sea_turtle", "octopus", "clownfish", "kelp_forest"],
        hunt_challenges=[
            ("aop_otter", "Sea otter: snack on the belly or a back float?"),
            ("aop_puffin", "Tufted puffin: beak empty or a fish stack?"),
            ("aop_shark", "Shark Lagoon: count the fins you can see at once."),
            ("aop_jelly", "Jelly Dreamscapes: watch one pulse from top to bottom."),
        ],
        display_names={
            "sea-otter": "Pacific sea otter",
            "puffin": "Tufted puffin",
            "shark": "Shark Lagoon shark",
            "stingray": "Pacific stingray",
            "jellyfish": "Jelly Dreamscapes jelly",
            "sea-turtle": "Olive Ridley sea turtle",
            "octopus": "Giant Pacific octopus",
            "clownfish": "Tropical Reef clownfish",
            "eel": "Pacific moray eel",
            "kelp-forest": "Casino Point kelp forest",
        },
        treasure=[
            "Watch a southern sea otter float or snack",
            "Find a tufted puffin with a beak of fish",
            "Count Shark Lagoon fins",
            "Watch a ray glide by",
            "Slow down in Jelly Dreamscapes",
            "Spot an Olive Ridley sea turtle",
            "Find a giant Pacific octopus hide",
            "Pick an Aquarium of the Pacific favorite — draw it later",
        ],
    )

    apply_kit(
        "audubon-aquarium",
        verified=False,
        tagline="Starter list: African penguins, then Shark Discovery and cownose rays.",
        items=[
            item("african-penguin", zone="Penguin gallery", one="African / South African penguin — waddle, then zoom.", core=True),
            item("shark", zone="Shark Discovery", one="Shark Discovery — watch the swim.", core=True),
            item("stingray", zone="Maya Tunnel / touch", one="Cownose rays and Maya Tunnel stingrays.", core=True),
        ],
        bans=bans_except(set(), [
            ("asian-small-clawed-otter", "Official animals directory otter is river otter (zoo-side), not Asian small-clawed."),
            ("sea-otter", "Not named on the official aquarium landing."),
            ("caribbean-flamingo", "Flamingo (if any) is on the combined zoo directory, not the aquarium landing."),
            ("two-toed-sloth", "Sloth (if any) is on the combined zoo directory, not the aquarium landing."),
            ("clownfish", "Not named on the official aquarium landing."),
            ("octopus", "Not named on the official aquarium landing."),
            ("jellyfish", "Moon jellies sit on a mixed zoo+aquarium directory — not isolated here."),
        ]),
        sources=[
            "https://audubonnatureinstitute.org/aquarium",
            "https://audubonnatureinstitute.org/animals",
        ],
        notes="[2026-08-23] Wave 4: official aquarium landing only. Combined zoo+aquarium directory not used for extra cards. Short overlap. No invented verify date.",
        hunt_tag="Audubon Aquarium bonus · penguins + sharks + rays",
        hunt_finds=[],
        hunt_challenges=[
            ("aud_penguin", "African penguin: watch one bird enter or leave the water."),
            ("aud_shark", "Shark Discovery: count the fins you can see at once."),
            ("aud_ray", "Cownose ray: glide, rest, or a splash?"),
        ],
        display_names={
            "african-penguin": "Audubon African penguin",
            "shark": "Shark Discovery shark",
            "stingray": "Audubon cownose ray",
        },
        treasure=[
            "Watch an African penguin zoom underwater",
            "Find a Shark Discovery fin",
            "Watch a cownose ray glide",
            "Pick an Audubon Aquarium favorite — draw it later",
        ],
    )

    apply_kit(
        "childrens-aquarium-dallas",
        verified=False,
        tagline="Starter Fair Park list: nurse sharks, cownose rays, then a giant Pacific octopus.",
        items=[
            item("shark", zone="Main galleries", one="Nurse and sandbar sharks — first big fish for little kids.", core=True),
            item("stingray", zone="Touch tank", one="Cownose stingrays — gentle hands if the pool is open.", core=True),
            item("octopus", zone="Main galleries", one="Giant Pacific octopus — check the corners.", core=True),
            item("sea-turtle", zone="Main galleries", one="Loggerhead sea turtle — flippers, not feet.", core=True),
            item("freshwater-fish", zone="Freshwater", one="Australian rainbows and blind cavefish — look for a flash.", core=True),
            item("starfish", zone="Touch tank", one="Touch-tank sea stars with urchins (if open).", core=False),
            item("eel", zone="Main galleries", one="Graceful eels — a long stare from a rocky hole.", core=False),
        ],
        bans=bans_except(set(), [
            ("crab", "Official touch tank names horseshoe crabs — not the crab card."),
            ("jellyfish", "Not named on official animal-exhibits pages."),
            ("seahorse", "Not named on official animal-exhibits pages."),
            ("clownfish", "Not named on official animal-exhibits pages."),
            ("asian-small-clawed-otter", "No otter on the official Children's Aquarium Dallas list."),
            ("two-toed-sloth", "DWA rainforest leftover — not a Fair Park animal."),
        ]),
        sources=[
            "https://www.childrensaquarium.com/",
            "https://www.childrensaquarium.com/animal-exhibits/",
        ],
        notes="[2026-08-23] Wave 4: official childrensaquarium.com homepage + animal-exhibits. Small-tank list, not a DWA clone. No invented verify date.",
        hunt_tag="CAD bonus · sharks + rays + octopus",
        hunt_finds=["sea_turtle", "freshwater_fish", "starfish", "eel"],
        hunt_challenges=[
            ("cad_shark", "Shark tank: count the fins you can see at once."),
            ("cad_ray", "Cownose ray: glide, rest, or a splash?"),
            ("cad_octo", "Giant Pacific octopus: how long until you spot an arm?"),
            ("cad_turtle", "Loggerhead: flippers busy or a still float?"),
        ],
        display_names={
            "shark": "Fair Park shark",
            "stingray": "Fair Park cownose ray",
            "octopus": "Fair Park octopus",
            "sea-turtle": "Loggerhead sea turtle",
            "freshwater-fish": "Fair Park freshwater fish",
            "starfish": "Touch-tank sea star",
            "eel": "Fair Park eel",
        },
        treasure=[
            "Find a Fair Park shark",
            "Watch a cownose ray in the touch tank",
            "Find a giant Pacific octopus hide",
            "Spot a loggerhead sea turtle",
            "Look for a flash of freshwater fish",
            "Find a touch-tank sea star",
            "Pick a Children's Aquarium Dallas favorite — draw it later",
        ],
    )

    apply_kit(
        "dallas-world-aquarium",
        verified=True,
        tagline="Sloth Forest first, then South Africa black-footed penguins and American flamingos — no lemur card.",
        items=[
            item("two-toed-sloth", zone="Sloth Forest / Orinoco", one="Hoffman's two-toed sloth — hang and look twice. Sloth Forest also names three-toed.", core=True, label="Sloth", note="Official: Hoffman's two-toed sloth page + Sloth Forest three-toed. Soft Sloth."),
            item("african-penguin", zone="South Africa / Cape of Good Hope", one="Black-footed penguin — official copy also calls it African / Jackass penguin.", core=True, note="Official animal page: Spheniscus demersus, also known as African penguin."),
            item("caribbean-flamingo", zone="Birds", one="American flamingo flock — long legs in the shallows.", core=True, label="Flamingo", note="Official: American flamingo (Phoenicopterus ruber). Soft Flamingo."),
            item("shark", zone="Mundo Maya / Aquarium", one="Mundo Maya sharks — don't miss the sharks.", core=True),
            item("stingray", zone="Aquarium", one="Eagle and river rays on the official animals directory.", core=True),
            item("jellyfish", zone="Aquarium", one="Moon jellyfish — watch them pulse.", core=True),
            item("octopus", zone="Aquarium", one="Giant Pacific octopus — check the corners.", core=False),
            item("seahorse", zone="Aquarium", one="Seahorses on the official animals directory.", core=False),
            item("clownfish", zone="Aquarium", one="Clownfish on the official animals directory.", core=False),
            item("cuttlefish", zone="Aquarium", one="Flamboyant cuttlefish — a living disguise.", core=False),
        ],
        bans=bans_except(set(), [
            ("ring-tailed-lemur", "Zoo-only card — drop even though Madagascar / lemur copy exists on site."),
            ("asian-small-clawed-otter", "Official otter is giant otter, not Asian small-clawed."),
            ("sea-otter", "Official otter is giant otter, not sea otter."),
            ("sea-turtle", "Official turtles are freshwater (arrau, mata mata), not sea turtles."),
        ]),
        sources=[
            "https://www.dwazoo.com/",
            "https://dwazoo.com/exhibit/sloth-forest/",
            "https://dwazoo.com/animal/hoffmans-two-toed-sloth/",
            "https://dwazoo.com/animal/black-footed-penguin/",
            "https://dwazoo.com/animal/american-flamingo/",
            "https://dwazoo.com/wp-content/uploads/2024/05/DWA-Field-Guide-2024.pdf",
        ],
        notes="[2026-08-23] Official-source Wave 4 public list pass (dwazoo.com animal directory + Sloth Forest + field guide). Ring-tailed lemur dropped as zoo-only.",
        hunt_tag="DWA bonus · Sloth Forest + South Africa + Mundo Maya",
        hunt_finds=["shark", "stingray", "jellyfish", "octopus", "seahorse", "cuttlefish"],
        hunt_challenges=[
            ("dwa_sloth", "Sloth Forest: mid-reach or statue-still?"),
            ("dwa_penguin", "Black-footed penguin: waddle or a water zoom?"),
            ("dwa_flam", "American flamingos: more than half on one leg?"),
            ("dwa_shark", "Mundo Maya: count the fins you can see at once."),
        ],
        display_names={
            "two-toed-sloth": "Sloth Forest sloth",
            "african-penguin": "Black-footed penguin",
            "caribbean-flamingo": "American flamingo",
            "shark": "Mundo Maya shark",
            "stingray": "DWA stingray",
            "jellyfish": "DWA moon jelly",
            "octopus": "DWA octopus",
            "seahorse": "DWA seahorse",
            "clownfish": "DWA clownfish",
            "cuttlefish": "Flamboyant cuttlefish",
        },
        treasure=[
            "Hang-and-look-twice at a Sloth Forest sloth",
            "Watch a black-footed penguin zoom underwater",
            "Count American flamingos on one leg",
            "Find a Mundo Maya shark",
            "Watch a ray glide by",
            "Slow down at the moon jellies",
            "Find a flamboyant cuttlefish disguise",
            "Pick a Dallas World Aquarium favorite — draw it later",
        ],
    )

    apply_kit(
        "dubai-aquarium",
        official_url="https://www.thedubaiaquarium.com/",
        verified=False,
        tagline="Starter list: Asian small-clawed otters, then the tunnel sharks and rays — Gentoo penguins, not African.",
        items=[
            item("asian-small-clawed-otter", zone="Underwater Zoo", one="Asian small-clawed otter encounter — smallest otter, biggest splash.", core=True),
            item("shark", zone="Tunnel", one="Tunnel sharks — watch the swim from below.", core=True),
            item("stingray", zone="Ray Encounter", one="Ray Encounter — flat swimmers glide by.", core=True),
            item("seahorse", zone="Underwater Zoo", one="Graceful seahorses in the Underwater Zoo.", core=False),
            item("freshwater-fish", zone="Underwater Zoo", one="Piranhas — look for a flash in the water.", core=False),
        ],
        bans=bans_except(set(), [
            ("african-penguin", "Official Penguin Cove is Gentoo penguin."),
            ("sea-otter", "Official otter is Asian small-clawed, not sea otter."),
            ("two-toed-sloth", "Sloths are mentioned; species unnamed — not mapped."),
            ("sea-turtle", "Not named on official encounter / ticket pages reviewed."),
            ("clownfish", "Not named on official public pages reviewed."),
            ("jellyfish", "Not named on official public pages reviewed."),
            ("octopus", "Not named on official public pages reviewed."),
        ]),
        sources=[
            "https://www.thedubaiaquarium.com/",
            "https://www.thedubaiaquarium.com/experiences/otter-encounter/",
            "https://www.thedubaiaquarium.com/experiences/ray-encounter/",
            "https://www.thedubaiaquarium.com/addon/shark-trainer-encounter/",
        ],
        notes="[2026-08-23] Wave 4: thedubaiaquarium.com encounters + ticket copy. No public species inventory. Short overlap. No invented verify date.",
        hunt_tag="Dubai bonus · otters + tunnel sharks + rays",
        hunt_finds=["seahorse", "freshwater_fish"],
        hunt_challenges=[
            ("dxb_otter", "Asian small-clawed otter: find the splashiest 10 seconds."),
            ("dxb_shark", "Tunnel shark: count the fins you can see at once."),
            ("dxb_ray", "Ray: glide, rest, or a splash?"),
        ],
        display_names={
            "asian-small-clawed-otter": "Dubai otter",
            "shark": "Tunnel shark",
            "stingray": "Dubai ray",
            "seahorse": "Dubai seahorse",
            "freshwater-fish": "Dubai piranha",
        },
        treasure=[
            "Watch Asian small-clawed otters splash",
            "Count tunnel-shark fins",
            "Watch a ray glide by",
            "Find a seahorse hold-on",
            "Pick a Dubai Aquarium favorite — draw it later",
        ],
    )

    apply_kit(
        "florida-aquarium",
        verified=False,
        tagline="Starter list: African penguins, then a two-toed sloth and moon jellies — river otters, not sea otters.",
        items=[
            item("african-penguin", zone="Penguin Encounter / habitats", one="African penguin — waddle, then zoom in the water.", core=True),
            item("two-toed-sloth", zone="Sloth Encounter", one="Two-toed sloth — hang and look twice.", core=True),
            item("jellyfish", zone="Moon Bay", one="Moon Bay moon jellies — watch them pulse.", core=True),
            item("shark", zone="Coral Reefs", one="Sand tiger shark in Coral Reefs.", core=True),
            item("stingray", zone="Stingray Beach / Coral Reefs", one="Southern stingray and spotted eagle rays.", core=True),
            item("sea-turtle", zone="Heart of the Sea", one="Loggerhead sea turtle — flippers, not feet.", core=True),
            item("octopus", zone="Waves of Wonder", one="Giant Pacific octopus — check the corners.", core=False),
            item("clownfish", zone="Heart of the Sea", one="Clownfish in Heart of the Sea / Waves of Wonder.", core=False),
            item("seahorse", zone="Reef Secrets", one="Pot-bellied and dwarf seahorse.", core=False),
            item("eel", zone="Coral Reefs / Shorelines", one="Moray and garden eels — a long stare from a hole.", core=False),
        ],
        bans=bans_except(set(), [
            ("asian-small-clawed-otter", "Official Wetlands otter is North American river otter."),
            ("sea-otter", "Official otter is North American river otter, not sea otter."),
            ("ring-tailed-lemur", "Lemur Lookout may exist; zoo-only card — never list."),
        ]),
        sources=[
            "https://www.flaquarium.org/",
            "https://www.flaquarium.org/explore/habitats/",
            "https://www.flaquarium.org/visit/experiences/penguin-encounter/",
            "https://www.flaquarium.org/visit/experiences/sloth-encounter/",
        ],
        notes="[2026-08-23] Wave 4: official flaquarium.org habitats + encounters. Spotlight list, not a full inventory. No invented verify date.",
        hunt_tag="Florida bonus · penguins + sloth + Moon Bay",
        hunt_finds=["shark", "stingray", "sea_turtle", "octopus", "clownfish", "seahorse"],
        hunt_challenges=[
            ("fla_penguin", "African penguin: watch one bird enter or leave the water."),
            ("fla_sloth", "Two-toed sloth: mid-reach or statue-still?"),
            ("fla_jelly", "Moon Bay: watch one pulse from top to bottom."),
            ("fla_turtle", "Loggerhead: flippers busy or a still float?"),
        ],
        display_names={
            "african-penguin": "Florida African penguin",
            "two-toed-sloth": "Florida sloth",
            "jellyfish": "Moon Bay jelly",
            "shark": "Coral Reefs shark",
            "stingray": "Stingray Beach ray",
            "sea-turtle": "Heart of the Sea turtle",
            "octopus": "Waves of Wonder octopus",
            "clownfish": "Florida clownfish",
            "seahorse": "Reef Secrets seahorse",
            "eel": "Florida eel",
        },
        treasure=[
            "Watch an African penguin zoom underwater",
            "Hang-and-look-twice at a two-toed sloth",
            "Slow down at Moon Bay jellies",
            "Find a Coral Reefs shark",
            "Watch a ray at Stingray Beach",
            "Spot a loggerhead sea turtle",
            "Find a giant Pacific octopus hide",
            "Pick a Florida Aquarium favorite — draw it later",
        ],
    )

    apply_kit(
        "georgia-aquarium",
        verified=True,
        tagline="Whale sharks and manta rays first, then African penguins — southern sea otters, not a generic otter.",
        items=[
            item("whale-shark", zone="Ocean Voyager", one="Home of the whale sharks — look for the biggest fish in the tank.", core=True),
            item("manta-ray", zone="Ocean Voyager", one="Manta rays glide by the tunnel like underwater birds.", core=True),
            item("african-penguin", zone="Cold Water Quest", one="African penguin colony — more than 25 nesting areas.", core=True),
            item("sea-otter", zone="Cold Water Quest", one="Southern sea otter — deck view plus a sneak-peek window.", core=True),
            item("asian-small-clawed-otter", zone="Animal guide", one="Asian small-clawed otter on the official animal guide.", core=True),
            item("shark", zone="Ocean Voyager", one="Reef and other sharks share Ocean Voyager with the whale sharks.", core=True),
            item("puffin", zone="Cold Water Quest", one="Horned and tufted puffin on the official animal guide.", core=False),
            item("octopus", zone="Tropical Diver", one="A camouflage master — look carefully.", core=False),
            item("jellyfish", zone="Cold Water Quest", one="Soft glow jellies in the cold-water rooms.", core=False),
            item("sea-turtle", zone="Ocean Voyager", one="Sea turtles paddle past the tunnel windows.", core=False),
        ],
        bans=bans_except(set(), [
            ("kelp-forest", "Kelp-associated fish appear; no official kelp-forest exhibit named."),
            ("caribbean-flamingo", "Not on the official animal guide reviewed."),
            ("two-toed-sloth", "Not on the official animal guide reviewed."),
            ("cuttlefish", "Not named as a public exhibit animal on pages reviewed."),
        ]),
        sources=[
            "https://www.georgiaaquarium.org/",
            "https://www.georgiaaquarium.org/animal-guide/",
            "https://www.georgiaaquarium.org/gallery/ocean-voyager/",
            "https://www.georgiaaquarium.org/gallery/cold-water-quest/",
        ],
        notes="[2026-08-23] Official-source Wave 4 public list pass (georgiaaquarium.org animal guide + galleries). Distinctive cards: whale-shark, manta-ray, sea-otter.",
        hunt_tag="Georgia bonus · Ocean Voyager + Cold Water Quest",
        hunt_finds=["sea_otter", "asian_small_clawed_otter", "shark", "puffin", "octopus", "jellyfish"],
        hunt_challenges=[
            ("ga_whale", "Whale shark: who looks biggest in the tunnel?"),
            ("ga_manta", "Manta ray: winged glide or a banked turn?"),
            ("ga_penguin", "African penguin: watch one bird enter or leave the water."),
            ("ga_otter", "Southern sea otter: snack on the belly or a back float?"),
        ],
        display_names={
            "whale-shark": "Ocean Voyager whale shark",
            "manta-ray": "Ocean Voyager manta ray",
            "african-penguin": "Cold Water Quest penguin",
            "sea-otter": "Georgia sea otter",
            "asian-small-clawed-otter": "Georgia otter",
            "shark": "Ocean Voyager shark",
            "puffin": "Georgia puffin",
            "octopus": "Tropical Diver octopus",
            "jellyfish": "Georgia jelly",
            "sea-turtle": "Ocean Voyager sea turtle",
        },
        treasure=[
            "Find the biggest whale shark in Ocean Voyager",
            "Watch a manta ray glide through the tunnel",
            "Watch an African penguin zoom underwater",
            "Watch a southern sea otter float or snack",
            "Find Asian small-clawed otters splash",
            "Count Ocean Voyager fins",
            "Find a puffin with a beak of fish",
            "Pick a Georgia Aquarium favorite — draw it later",
        ],
    )

    apply_kit(
        "istanbul-aquarium",
        verified=False,
        tagline="Starter list: lemon and sand-tiger sharks, then cownose rays and clownfish — Gentoo penguins, not African.",
        items=[
            item("shark", zone="Themes", one="Lemon shark and sand tiger shark on the official creatures list.", core=True),
            item("stingray", zone="Themes", one="Cownose and eagle rays.", core=True),
            item("clownfish", zone="Themes", one="Palyaço balığı — Amphiprion ocellaris.", core=True),
            item("eel", zone="Mediterranean / themes", one="Mediterranean moray and spotted garden moray.", core=True),
            item("sea-turtle", zone="West Atlantic", one="Loggerhead (Caretta caretta) in the West Atlantic tank.", core=True),
            item("seahorse", zone="Aegean", one="Seahorse in the Aegean theme.", core=False),
            item("freshwater-fish", zone="Amazon", one="Red-bellied piranha and endemic toothcarp.", core=False),
        ],
        bans=bans_except(set(), [
            ("african-penguin", "Official homepage / creatures hub: Gentoo penguin."),
            ("asian-small-clawed-otter", "Not named on official popular-animals pages."),
            ("jellyfish", "Not on the published popular-animals list reviewed."),
            ("octopus", "Not on the published popular-animals list reviewed."),
        ]),
        sources=[
            "https://www.istanbulakvaryum.com/en",
            "https://www.istanbulakvaryum.com/canlilar",
            "https://www.istanbulakvaryum.com/temalar",
        ],
        notes="[2026-08-23] Wave 4: istanbulakvaryum.com popular animals + themes. Not the claimed 1,500-species list. No invented verify date.",
        hunt_tag="Istanbul bonus · sharks + rays + clownfish",
        hunt_finds=["eel", "sea_turtle", "seahorse", "freshwater_fish"],
        hunt_challenges=[
            ("ist_shark", "Shark: count the fins you can see at once."),
            ("ist_ray", "Cownose ray: glide, rest, or a splash?"),
            ("ist_clown", "Clownfish: who hides in the anemone first?"),
            ("ist_turtle", "Loggerhead: flippers busy or a still float?"),
        ],
        display_names={
            "shark": "Istanbul shark",
            "stingray": "Istanbul ray",
            "clownfish": "Istanbul clownfish",
            "eel": "Istanbul moray",
            "sea-turtle": "West Atlantic loggerhead",
            "seahorse": "Aegean seahorse",
            "freshwater-fish": "Amazon fish",
        },
        treasure=[
            "Find a lemon or sand-tiger shark",
            "Watch a cownose ray glide",
            "Find a clownfish in an anemone",
            "Spot a Mediterranean moray",
            "Find a West Atlantic loggerhead",
            "Pick an Istanbul Aquarium favorite — draw it later",
        ],
    )

    apply_kit(
        "lotte-aquarium-seoul",
        official_url="https://aquarium.lotteworld.com/",
        verified=False,
        tagline="Starter list: sand-tiger sharks and rays in the main tank — Humboldt penguins, not African.",
        items=[
            item("shark", zone="Main tank", one="Sand tiger sharks — Shark & Ray Mukbang tank.", core=True),
            item("stingray", zone="Main tank", one="Rays share the main tank with the sharks.", core=True),
        ],
        bans=bans_except(set(), [
            ("african-penguin", "Official Polar Zone talk is Humboldt penguin."),
            ("asian-small-clawed-otter", "Otter talk exists; species unnamed — not mapped."),
            ("jellyfish", "Not named on official public pages reviewed."),
            ("sea-turtle", "Not named on official public pages reviewed."),
            ("clownfish", "Not named on official public pages reviewed."),
            ("octopus", "Not named on official public pages reviewed."),
            ("seahorse", "Not named on official public pages reviewed."),
            ("freshwater-fish", "Not named on official public pages reviewed."),
        ]),
        sources=[
            "https://aquarium.lotteworld.com/",
            "https://aquarium.lotteworld.com/enjoy/participating-programs/list",
        ],
        notes="[2026-08-23] Wave 4: aquarium.lotteworld.com SPA. Only sharks and rays named on public program copy. Short overlap. No invented verify date.",
        hunt_tag="Lotte bonus · main-tank sharks + rays",
        hunt_finds=[],
        hunt_challenges=[
            ("lot_shark", "Main tank: count the fins you can see at once."),
            ("lot_ray", "Ray: glide, rest, or a splash?"),
        ],
        display_names={
            "shark": "Lotte sand tiger shark",
            "stingray": "Lotte ray",
        },
        treasure=[
            "Find a sand tiger shark in the main tank",
            "Watch a ray glide by",
            "Pick a Lotte Aquarium favorite — draw it later",
        ],
    )

    apply_kit(
        "milan-aquarium",
        official_url="https://www.acquariodimilano.it/",
        verified=False,
        tagline="Starter civic list: Po-plain freshwater fish, then jellies and stingrays.",
        items=[
            item("freshwater-fish", zone="Percorso espositivo", one="Trout, tench, and sturgeon in the Po-plain basins.", core=True),
            item("jellyfish", zone="Percorso espositivo", one="Meduse — watch them pulse.", core=True),
            item("stingray", zone="Bridge tank", one="Trigoni in the bridge tank.", core=True),
            item("shark", zone="Bridge tank", one="Leopard / zebra sharks (squali gattopardo) in a small civic tank.", core=False),
        ],
        bans=bans_except(set(), [
            ("sea-turtle", "Official turtles page is freshwater turtles, not sea turtles."),
            ("clownfish", "Red Sea tank exists; clownfish not named."),
            ("seahorse", "Not named on official percorso pages."),
            ("octopus", "Not named on official percorso pages."),
            ("asian-small-clawed-otter", "Not on the official civic aquarium route."),
        ]),
        sources=[
            "https://www.acquariodimilano.it/",
            "https://www.acquariodimilano.it/acquario/percorso-espositivo",
        ],
        notes="[2026-08-23] Wave 4: acquariodimilano.it percorso (acquariocivicomilano.eu is parked). Thin civic list. No invented verify date.",
        hunt_tag="Milan bonus · freshwater + jellies + rays",
        hunt_finds=["shark"],
        hunt_challenges=[
            ("mil_fish", "Po-plain fish: look for a flash of silver."),
            ("mil_jelly", "Meduse: watch one pulse from top to bottom."),
            ("mil_ray", "Trigoni: glide, rest, or a splash?"),
        ],
        display_names={
            "freshwater-fish": "Po-plain fish",
            "jellyfish": "Milan jelly",
            "stingray": "Bridge-tank ray",
            "shark": "Milan leopard shark",
        },
        treasure=[
            "Spot a flash of Po-plain fish",
            "Slow down at the meduse",
            "Watch a bridge-tank ray",
            "Find a small civic-tank shark",
            "Pick an Acquario di Milano favorite — draw it later",
        ],
    )

    apply_kit(
        "monterey-bay-aquarium",
        verified=True,
        tagline="Jellies first, then southern sea otters and the Kelp Forest — Magellanic penguins are not a Start here.",
        items=[
            item("jellyfish", zone="Jellies / Into the Deep", one="Famous glowing jellies — slow down and watch them drift.", core=True),
            item("sea-otter", zone="Sea Otters", one="Southern sea otter — romp, tumble, and a back-float snack.", core=True),
            item("kelp-forest", zone="Kelp Forest", one="28-foot kelp forest — sardines, leopard sharks, and wolf-eels.", core=True),
            item("shark", zone="Kelp Forest / Monterey Bay Habitats", one="Leopard and swell sharks weave through kelp and sandy seafloor.", core=True),
            item("sea-turtle", zone="Open Sea", one="Sea turtles drift past the 90-foot Open Sea windows.", core=True),
            item("octopus", zone="Giant Pacific octopus", one="Giant Pacific octopus — master of disguise.", core=True),
            item("puffin", zone="Open Sea", one="Tufted puffin on official Open Sea animal links.", core=False),
            item("stingray", zone="Touch / habitats", one="Rays on official habitat pages — gentle hands if a pool is open.", core=False),
            item("starfish", zone="Rocky Shore", one="Sea stars on the rocky shore.", core=False),
            item("eel", zone="Kelp Forest", one="Wolf-eel among the kelp.", core=False),
        ],
        bans=bans_except(set(), [
            ("clownfish", "Not named on official exhibit pages reviewed."),
            ("seahorse", "Official names pipefish, not seahorse."),
            ("african-penguin", "No African penguin exhibit on the official exhibits list."),
            ("asian-small-clawed-otter", "Official otter is southern sea otter."),
            ("freshwater-fish", "Not named on official exhibit pages reviewed."),
        ]),
        sources=[
            "https://www.montereybayaquarium.org/visit/exhibits",
            "https://www.montereybayaquarium.org/visit/exhibits/kelp-forest",
            "https://www.montereybayaquarium.org/visit/exhibits/sea-otters",
            "https://www.montereybayaquarium.org/visit/exhibits/open-sea",
            "https://www.montereybayaquarium.org/visit/exhibits/giant-pacific-octopus",
        ],
        notes="[2026-08-23] Official-source Wave 4 public list pass (montereybayaquarium.org exhibits). Distinctive cards: jellyfish, sea-otter, kelp-forest.",
        hunt_tag="Monterey bonus · jellies + sea otters + Kelp Forest",
        hunt_finds=["shark", "sea_turtle", "octopus", "puffin", "stingray", "starfish"],
        hunt_challenges=[
            ("mba_jelly", "Jellies: watch one pulse from top to bottom."),
            ("mba_otter", "Sea otter: snack on the belly or a back float?"),
            ("mba_kelp", "Kelp Forest: count the fish you can see in one glance."),
            ("mba_octo", "Giant Pacific octopus: how long until you spot an arm?"),
        ],
        display_names={
            "jellyfish": "Monterey jelly",
            "sea-otter": "Monterey sea otter",
            "kelp-forest": "Kelp Forest",
            "shark": "Monterey shark",
            "sea-turtle": "Open Sea turtle",
            "octopus": "Giant Pacific octopus",
            "puffin": "Tufted puffin",
            "stingray": "Monterey ray",
            "starfish": "Rocky Shore sea star",
            "eel": "Wolf-eel",
        },
        treasure=[
            "Slow down at the jellies",
            "Watch a southern sea otter float or snack",
            "Look up through the Kelp Forest",
            "Find a leopard or swell shark",
            "Spot an Open Sea turtle",
            "Find a giant Pacific octopus hide",
            "Find a tufted puffin",
            "Pick a Monterey favorite — draw it later",
        ],
    )

    apply_kit(
        "national-aquarium-baltimore",
        verified=True,
        tagline="Atlantic puffins first, then a rainforest two-toed sloth and Jellies Invasion — no African penguin on the directory.",
        items=[
            item("puffin", zone="North Atlantic", one="Atlantic puffin — a triangular red-orange bill.", core=True),
            item("two-toed-sloth", zone="Upland Tropical Rain Forest", one="Linne's two-toed sloth — hang and look twice.", core=True),
            item("jellyfish", zone="Jellies Invasion", one="Jellies Invasion — watch them pulse.", core=True),
            item("shark", zone="Blacktip Reef / Shark Alley", one="Blacktip reef shark and Shark Alley.", core=True),
            item("stingray", zone="Animals", one="Atlantic stingray and Australian whipray.", core=True),
            item("octopus", zone="Animals", one="Octopus on the official 86-animal directory.", core=True),
            item("sea-turtle", zone="Animals", one="Green and Kemp’s ridley sea turtles.", core=False),
            item("clownfish", zone="Animals", one="Percula clownfish on the official directory.", core=False),
            item("starfish", zone="Living Seashore", one="Sea stars on the official directory.", core=False),
            item("eel", zone="Animals", one="Eels on the official directory.", core=False),
        ],
        bans=bans_except(set(), [
            ("african-penguin", "Not on the official aqua.org animals directory; puffins are the featured alcid."),
            ("seahorse", "Not on the official 86-animal directory reviewed."),
            ("asian-small-clawed-otter", "Not on the official animals directory."),
            ("sea-otter", "Not on the official animals directory."),
            ("caribbean-flamingo", "Not on the official animals directory."),
        ]),
        sources=[
            "https://aqua.org/explore/animals",
            "https://aqua.org/explore/exhibits",
            "https://aqua.org/explore/exhibits/north-atlantic-to-the-pacific",
        ],
        notes="[2026-08-23] Official-source Wave 4 public list pass (aqua.org animals directory). African penguin leftover dropped.",
        hunt_tag="National Aquarium bonus · puffin + sloth + jellies",
        hunt_finds=["shark", "stingray", "octopus", "sea_turtle", "clownfish", "starfish"],
        hunt_challenges=[
            ("na_puffin", "Atlantic puffin: beak empty or a fish stack?"),
            ("na_sloth", "Rainforest sloth: mid-reach or statue-still?"),
            ("na_jelly", "Jellies Invasion: watch one pulse from top to bottom."),
            ("na_shark", "Blacktip Reef: count the fins you can see at once."),
        ],
        display_names={
            "puffin": "Atlantic puffin",
            "two-toed-sloth": "Rainforest sloth",
            "jellyfish": "Jellies Invasion",
            "shark": "Blacktip reef shark",
            "stingray": "National Aquarium ray",
            "octopus": "National Aquarium octopus",
            "sea-turtle": "National Aquarium sea turtle",
            "clownfish": "Percula clownfish",
            "starfish": "Living Seashore sea star",
            "eel": "National Aquarium eel",
        },
        treasure=[
            "Find an Atlantic puffin",
            "Hang-and-look-twice at a rainforest sloth",
            "Slow down at Jellies Invasion",
            "Count Blacktip Reef fins",
            "Watch a ray glide by",
            "Find an octopus hide",
            "Spot a sea turtle",
            "Pick a National Aquarium favorite — draw it later",
        ],
    )

    apply_kit(
        "new-england-aquarium",
        verified=False,
        tagline="Starter list: African penguins, then Myrtle the green sea turtle and Giant Ocean Tank sharks.",
        items=[
            item("african-penguin", zone="Penguin Colony", one="About 50 African and southern rockhopper penguins — start with the African colony.", core=True),
            item("sea-turtle", zone="Giant Ocean Tank", one="Myrtle the green sea turtle — flippers, not feet.", core=True),
            item("shark", zone="Giant Ocean Tank / Science of Sharks", one="Epaulette shark plus Giant Ocean Tank sharks.", core=True),
            item("stingray", zone="Shark and Ray Touch Tank", one="Cownose ray — gentle hands if the pool is open.", core=True),
            item("jellyfish", zone="Sea Jellies", one="Sea Jellies — watch them pulse.", core=True),
            item("octopus", zone="Olympic Coast", one="Giant Pacific octopus on the Olympic Coast.", core=True),
            item("seahorse", zone="Animals", one="Dwarf seahorse on the official animals page.", core=False),
            item("clownfish", zone="Animals", one="Anemonefish on the official animals page.", core=False),
            item("freshwater-fish", zone="Amazon Rainforest", one="Piranha in the Amazon Rainforest.", core=False),
        ],
        bans=bans_except(set(), [
            ("eel", "Not named on the official 'few of the animals' page."),
            ("crab", "Not named on the official animals / exhibits pages reviewed."),
            ("starfish", "Not named on the official animals / exhibits pages reviewed."),
            ("asian-small-clawed-otter", "Not on the official animals page."),
            ("sea-otter", "Not on the official animals page."),
        ]),
        sources=[
            "https://www.neaq.org/animals/",
            "https://www.neaq.org/exhibits",
        ],
        notes="[2026-08-23] Wave 4: neaq.org animals page is explicitly 'a few of the animals.' Starter, no invented verify date.",
        hunt_tag="New England bonus · Penguin Colony + Myrtle + sharks",
        hunt_finds=["stingray", "jellyfish", "octopus", "seahorse", "clownfish", "freshwater_fish"],
        hunt_challenges=[
            ("nea_penguin", "African penguin: watch one bird enter or leave the water."),
            ("nea_myrtle", "Myrtle: flippers busy or a still float?"),
            ("nea_shark", "Giant Ocean Tank: count the fins you can see at once."),
            ("nea_jelly", "Sea Jellies: watch one pulse from top to bottom."),
        ],
        display_names={
            "african-penguin": "Penguin Colony African penguin",
            "sea-turtle": "Myrtle",
            "shark": "Giant Ocean Tank shark",
            "stingray": "Touch-tank cownose ray",
            "jellyfish": "Sea Jellies",
            "octopus": "Olympic Coast octopus",
            "seahorse": "Dwarf seahorse",
            "clownfish": "New England anemonefish",
            "freshwater-fish": "Amazon piranha",
        },
        treasure=[
            "Watch an African penguin zoom underwater",
            "Find Myrtle the green sea turtle",
            "Count Giant Ocean Tank fins",
            "Watch a cownose ray in the touch tank",
            "Slow down at Sea Jellies",
            "Find a giant Pacific octopus hide",
            "Pick a New England Aquarium favorite — draw it later",
        ],
    )

    apply_kit(
        "osaka-aquarium",
        verified=False,
        tagline="Starter list: whale shark, then Jellyfish Galaxy and a reef manta — Adelie penguins, not African.",
        items=[
            item("whale-shark", zone="Pacific Ocean", one="Kaiyukan whale shark — look for the biggest fish in the ring.", core=True),
            item("jellyfish", zone="Jellyfish Galaxy", one="海月銀河 — watch them pulse.", core=True),
            item("manta-ray", zone="Pacific Ocean", one="Reef manta (Mobula alfredi) shares the Pacific tank.", core=True),
            item("shark", zone="Pacific Ocean", one="Other sharks share the Pacific tank with the whale shark.", core=True),
            item("crab", zone="Japan Trench", one="Japanese giant spider crab.", core=True),
            item("octopus", zone="Seto Inland Sea", one="Common octopus — check the corners.", core=False),
            item("sea-turtle", zone="Pacific Ocean", one="Loggerhead sea turtle.", core=False),
            item("asian-small-clawed-otter", zone="Animals", one="Asian small-clawed otter (Aonyx cinerea) on the encyclopedia.", core=False),
            item("freshwater-fish", zone="Amazon", one="Amazon tropical fish — look for a flash.", core=False),
        ],
        bans=bans_except(set(), [
            ("african-penguin", "Official Antarctica tank is Adelie penguin."),
            ("stingray", "Official names eagle/manta rays, not stingray."),
            ("clownfish", "Not named on fetched official encyclopedia pages."),
            ("seahorse", "Not named on fetched official encyclopedia pages."),
            ("sea-otter", "Official otter is Asian small-clawed, not sea otter."),
        ]),
        sources=[
            "https://www.kaiyukan.com/language/eng/",
            "https://www.kaiyukan.com/about/beginner/",
            "https://www.kaiyukan.com/about/exhibition/kurage-ginga/",
        ],
        notes="[2026-08-23] Wave 4: kaiyukan.com English + Japanese encyclopedia highlights. English is thin. No invented verify date.",
        hunt_tag="Kaiyukan bonus · whale shark + Jellyfish Galaxy + manta",
        hunt_finds=["shark", "crab", "octopus", "sea_turtle", "asian_small_clawed_otter", "freshwater_fish"],
        hunt_challenges=[
            ("osa_whale", "Whale shark: who looks biggest in the ring?"),
            ("osa_jelly", "Jellyfish Galaxy: watch one pulse from top to bottom."),
            ("osa_manta", "Reef manta: winged glide or a banked turn?"),
            ("osa_crab", "Spider crab: count the legs you can see."),
        ],
        display_names={
            "whale-shark": "Kaiyukan whale shark",
            "jellyfish": "Jellyfish Galaxy",
            "manta-ray": "Reef manta",
            "shark": "Pacific tank shark",
            "crab": "Japanese spider crab",
            "octopus": "Seto Inland Sea octopus",
            "sea-turtle": "Kaiyukan loggerhead",
            "asian-small-clawed-otter": "Kaiyukan otter",
            "freshwater-fish": "Amazon fish",
        },
        treasure=[
            "Find the Kaiyukan whale shark",
            "Slow down in Jellyfish Galaxy",
            "Watch a reef manta glide",
            "Find a Japanese spider crab",
            "Spot a loggerhead sea turtle",
            "Watch Asian small-clawed otters splash",
            "Pick a Kaiyukan favorite — draw it later",
        ],
    )

    apply_kit(
        "seattle-aquarium",
        verified=False,
        tagline="Starter list: sea otters, tufted puffins, then a giant Pacific octopus — river otters are a different stop.",
        items=[
            item("sea-otter", zone="Mammals", one="Sea otter — floats, snacks, and steals the show.", core=True),
            item("puffin", zone="Birds", one="Tufted puffin — a beak full of fish.", core=True),
            item("octopus", zone="Invertebrates", one="Giant Pacific octopus — check the corners.", core=True),
            item("jellyfish", zone="Invertebrates", one="Jellies — watch them pulse.", core=True),
            item("cuttlefish", zone="Invertebrates", one="Dwarf cuttlefish — a living disguise.", core=True),
            item("shark", zone="Fish", one="Blacktip reef, dogfish, and Indo-Pacific leopard sharks.", core=True),
            item("stingray", zone="Fish", one="Blue-spotted, leopard whiptail, and spotted eagle rays.", core=False),
            item("seahorse", zone="Fish", one="Seahorses on the official animals page.", core=False),
            item("clownfish", zone="Fish", one="Clownfish on the official animals page.", core=False),
            item("starfish", zone="Invertebrates", one="Sea stars on the official animals page.", core=False),
        ],
        bans=bans_except(set(), [
            ("sea-turtle", "Not named on the official 'just a few' animals page."),
            ("asian-small-clawed-otter", "Official second otter is river otter, not Asian small-clawed."),
            ("african-penguin", "No penguin on the official animals page."),
        ]),
        sources=[
            "https://www.seattleaquarium.org/animals/",
        ],
        notes="[2026-08-23] Wave 4: seattleaquarium.org animals page is featured categories, not a full inventory. No invented verify date.",
        hunt_tag="Seattle bonus · sea otter + puffin + octopus",
        hunt_finds=["jellyfish", "cuttlefish", "shark", "stingray", "seahorse", "starfish"],
        hunt_challenges=[
            ("sea_otter", "Sea otter: snack on the belly or a back float?"),
            ("sea_puffin", "Tufted puffin: beak empty or a fish stack?"),
            ("sea_octo", "Giant Pacific octopus: how long until you spot an arm?"),
            ("sea_cuttle", "Dwarf cuttlefish: which color did it try first?"),
        ],
        display_names={
            "sea-otter": "Seattle sea otter",
            "puffin": "Tufted puffin",
            "octopus": "Giant Pacific octopus",
            "jellyfish": "Seattle jelly",
            "cuttlefish": "Dwarf cuttlefish",
            "shark": "Seattle shark",
            "stingray": "Seattle ray",
            "seahorse": "Seattle seahorse",
            "clownfish": "Seattle clownfish",
            "starfish": "Seattle sea star",
        },
        treasure=[
            "Watch a sea otter float or snack",
            "Find a tufted puffin",
            "Find a giant Pacific octopus hide",
            "Slow down at the jellies",
            "Find a dwarf cuttlefish disguise",
            "Count shark fins",
            "Pick a Seattle Aquarium favorite — draw it later",
        ],
    )

    apply_kit(
        "shanghai-ocean-aquarium",
        official_url="https://www.sh-aquarium.com/",
        verified=False,
        tagline="Starter list: Shark Bay, then a green sea turtle and Pacific sea nettles — Magellanic penguins, not African.",
        items=[
            item("shark", zone="Shark Bay", one="Sand tiger shark plus Shark Bay's named shark species.", core=True),
            item("sea-turtle", zone="Deep-sea tunnel", one="Green sea turtle in the deep-sea tunnel.", core=True),
            item("jellyfish", zone="Themes", one="Pacific sea nettle — watch them pulse.", core=True),
            item("stingray", zone="Themes", one="Cownose ray.", core=True),
            item("seahorse", zone="Themes", one="Big-belly seahorse (膨腹海马).", core=True),
            item("freshwater-fish", zone="Yangtze / Amazon / Africa", one="Freshwater galleries — look for a flash.", core=False),
            item("manta-ray", zone="Feeding", one="Mobulid / 蝠鲼科 flying-fish feeding.", core=False),
        ],
        bans=bans_except(set(), [
            ("african-penguin", "Official penguin is Magellanic (麦哲伦企鹅)."),
            ("asian-small-clawed-otter", "Not named on official exhibition-area pages."),
            ("eel", "Official electric-eel copy says it is not an eel."),
            ("clownfish", "Not named on official exhibition-area pages reviewed."),
            ("octopus", "Not named on official exhibition-area pages reviewed."),
        ]),
        sources=[
            "https://www.sh-aquarium.com/",
            "https://www.sh-aquarium.com/ExhibitionArea/index.aspx",
            "https://www.sh-aquarium.com/ParkNavigation/index.aspx",
        ],
        notes="[2026-08-23] Wave 4: sh-aquarium.com themed zones + featured species (aquarium.sh.com timed out). No invented verify date.",
        hunt_tag="Shanghai bonus · Shark Bay + tunnel turtle + nettles",
        hunt_finds=["stingray", "seahorse", "freshwater_fish", "manta_ray"],
        hunt_challenges=[
            ("sha_shark", "Shark Bay: count the fins you can see at once."),
            ("sha_turtle", "Green sea turtle: flippers busy or a still float?"),
            ("sha_jelly", "Pacific sea nettle: watch one pulse from top to bottom."),
            ("sha_horse", "Big-belly seahorse: tail wrapped or swimming free?"),
        ],
        display_names={
            "shark": "Shark Bay shark",
            "sea-turtle": "Tunnel green sea turtle",
            "jellyfish": "Pacific sea nettle",
            "stingray": "Shanghai cownose ray",
            "seahorse": "Big-belly seahorse",
            "freshwater-fish": "Yangtze / Amazon fish",
            "manta-ray": "Shanghai manta",
        },
        treasure=[
            "Find a Shark Bay shark",
            "Spot a green sea turtle in the tunnel",
            "Slow down at the Pacific sea nettles",
            "Watch a cownose ray glide",
            "Find a big-belly seahorse",
            "Pick a Shanghai Ocean Aquarium favorite — draw it later",
        ],
    )

    apply_kit(
        "shedd-aquarium",
        verified=True,
        tagline="Sea otters first, then Wild Reef sharks and jellies — rockhopper and Magellanic penguins, not African.",
        items=[
            item("sea-otter", zone="Abbott Oceanarium", one="Southern sea otter — floats, snacks, and steals the show.", core=True),
            item("shark", zone="Wild Reef", one="Blacktip reef, sandbar, wobbegong, and zebra sharks.", core=True),
            item("jellyfish", zone="Jellies / Wild Reef", one="Jellies plus upside-down jellies in Wild Reef.", core=True),
            item("stingray", zone="Animals", one="Stingrays on the official animals hub.", core=True),
            item("octopus", zone="Animals", one="Giant Pacific octopus on the official animals hub.", core=True),
            item("seahorse", zone="Animals", one="Seahorses on the official animals hub.", core=True),
            item("starfish", zone="Animals", one="Sea stars on the official animals hub.", core=False),
            item("cuttlefish", zone="Wild Reef", one="Flamboyant cuttlefish moved into refreshed Wild Reef.", core=False),
            item("freshwater-fish", zone="Animals", one="Freshwater fishes on the official animals hub.", core=False),
            item("sea-turtle", zone="Animals", one="Turtles on the official animals hub — look for flippers.", core=False),
        ],
        bans=bans_except(set(), [
            ("african-penguin", "Official penguins page: rockhopper and Magellanic only."),
            ("asian-small-clawed-otter", "Official otter is sea otter, not Asian small-clawed."),
        ]),
        sources=[
            "https://www.sheddaquarium.org/animals",
            "https://www.sheddaquarium.org/animals/penguins",
            "https://www.sheddaquarium.org/stories/meet-the-sea-otters",
            "https://www.sheddaquarium.org/stories/meet-the-sharks",
        ],
        notes="[2026-08-23] Official-source Wave 4 public list pass (sheddaquarium.org animals hub + penguins + otter/shark stories).",
        hunt_tag="Shedd bonus · sea otters + Wild Reef + jellies",
        hunt_finds=["stingray", "octopus", "seahorse", "starfish", "cuttlefish", "freshwater_fish"],
        hunt_challenges=[
            ("shd_otter", "Sea otter: snack on the belly or a back float?"),
            ("shd_shark", "Wild Reef: count the fins you can see at once."),
            ("shd_jelly", "Jellies: watch one pulse from top to bottom."),
            ("shd_cuttle", "Flamboyant cuttlefish: which color did it try first?"),
        ],
        display_names={
            "sea-otter": "Shedd sea otter",
            "shark": "Wild Reef shark",
            "jellyfish": "Shedd jelly",
            "stingray": "Shedd stingray",
            "octopus": "Shedd octopus",
            "seahorse": "Shedd seahorse",
            "starfish": "Shedd sea star",
            "cuttlefish": "Wild Reef cuttlefish",
            "freshwater-fish": "Shedd freshwater fish",
            "sea-turtle": "Shedd turtle",
        },
        treasure=[
            "Watch a Shedd sea otter float or snack",
            "Count Wild Reef shark fins",
            "Slow down at the jellies",
            "Watch a stingray glide",
            "Find a giant Pacific octopus hide",
            "Find a seahorse hold-on",
            "Find a flamboyant cuttlefish disguise",
            "Pick a Shedd favorite — draw it later",
        ],
    )

    apply_kit(
        "two-oceans-aquarium",
        verified=True,
        tagline="African penguins first, then ragged-tooth sharks and the Kelp Forest exhibit.",
        items=[
            item("african-penguin", zone="Penguin Exhibit", one="African penguin colony — plus rescued northern rockhopper nearby.", core=True),
            item("shark", zone="Predators / Kelp Forest", one="Ragged-tooth, shysharks, and kelp-forest sharks.", core=True),
            item("kelp-forest", zone="Kelp Forest Exhibit", one="Official Kelp Forest Exhibit — an underwater forest.", core=True),
            item("sea-turtle", zone="I&J Ocean Exhibit", one="Rescued sea turtles in I&J Ocean.", core=True),
            item("jellyfish", zone="Jellies", one="Moon jelly on display — watch them pulse.", core=True),
            item("stingray", zone="I&J Ocean Exhibit", one="Rays in I&J Ocean.", core=True),
            item("octopus", zone="Animals", one="Common octopus — check the corners.", core=False),
            item("clownfish", zone="Animals", one="Western clownfish / anemonefish.", core=False),
            item("seahorse", zone="Animals", one="Knysna seahorse.", core=False),
            item("eel", zone="Animals", one="Four official moray species.", core=False),
        ],
        bans=bans_except(set(), [
            ("asian-small-clawed-otter", "No otter on the official animals pages reviewed."),
            ("sea-otter", "No sea otter on the official animals pages."),
        ]),
        sources=[
            "https://www.aquarium.co.za/",
            "https://www.aquarium.co.za/animals/penguins",
            "https://www.aquarium.co.za/animals/sharks",
            "https://www.aquarium.co.za/animals/kelp-forest",
            "https://www.aquarium.co.za/animals/turtles",
        ],
        notes="[2026-08-23] Official-source Wave 4 public list pass (aquarium.co.za animals + exhibits).",
        hunt_tag="Two Oceans bonus · African penguins + sharks + kelp",
        hunt_finds=["sea_turtle", "jellyfish", "stingray", "octopus", "clownfish", "seahorse"],
        hunt_challenges=[
            ("toa_penguin", "African penguin: watch one bird enter or leave the water."),
            ("toa_shark", "Ragged-tooth shark: count the fins you can see at once."),
            ("toa_kelp", "Kelp Forest: count the fish you can see in one glance."),
            ("toa_turtle", "I&J Ocean turtle: flippers busy or a still float?"),
        ],
        display_names={
            "african-penguin": "Two Oceans African penguin",
            "shark": "Ragged-tooth shark",
            "kelp-forest": "Kelp Forest Exhibit",
            "sea-turtle": "I&J Ocean turtle",
            "jellyfish": "Two Oceans jelly",
            "stingray": "I&J Ocean ray",
            "octopus": "Common octopus",
            "clownfish": "Western clownfish",
            "seahorse": "Knysna seahorse",
            "eel": "Two Oceans moray",
        },
        treasure=[
            "Watch an African penguin zoom underwater",
            "Find a ragged-tooth shark",
            "Look through the Kelp Forest Exhibit",
            "Spot an I&J Ocean sea turtle",
            "Slow down at the moon jellies",
            "Watch a ray glide by",
            "Find a Knysna seahorse",
            "Pick a Two Oceans favorite — draw it later",
        ],
    )

    apply_kit(
        "vancouver-aquarium",
        verified=True,
        tagline="Northern sea otters first, then moon jellies and a rainforest two-toed sloth — no penguin on the directory.",
        items=[
            item("sea-otter", zone="Animals", one="Northern sea otter (Enhydra lutris) — floats and snacks.", core=True),
            item("jellyfish", zone="Animals", one="Moon jelly and Pacific sea nettle — watch them pulse.", core=True),
            item("two-toed-sloth", zone="Tropics", one="Linnaeus's two-toed sloth — hang and look twice.", core=True),
            item("octopus", zone="Treasures of the BC Coast", one="Giant Pacific octopus — check the corners.", core=True),
            item("shark", zone="Animals", one="Bamboo, blacktip reef, and epaulette sharks.", core=True),
            item("clownfish", zone="Tropics", one="Clown anemonefish.", core=True),
            item("stingray", zone="Animals", one="Reticulate whipray.", core=False),
            item("seahorse", zone="Animals", one="Barbour's seahorse.", core=False),
            item("starfish", zone="Wet Lab", one="Wet Lab sea stars.", core=False),
            item("freshwater-fish", zone="Animals", one="Arctic char, coho salmon, and white sturgeon.", core=False),
        ],
        bans=bans_except(set(), [
            ("asian-small-clawed-otter", "Official otter is northern sea otter."),
            ("african-penguin", "No penguin species on the official animals directory."),
            ("sea-turtle", "Official turtle is pig-nosed (freshwater), not a sea turtle."),
            ("eel", "Not named on official animals / exhibit pages reviewed."),
            ("crab", "Not named on official animals / exhibit pages reviewed."),
        ]),
        sources=[
            "https://www.vanaqua.org/explore/animals/",
            "https://www.vanaqua.org/explore/animals/sea-otters/",
            "https://vanaqua.org/explore/exhibits/",
            "https://vanaqua.org/explore/exhibits/tropics/",
        ],
        notes="[2026-08-23] Official-source Wave 4 public list pass (vanaqua.org animals + exhibits).",
        hunt_tag="Vancouver bonus · sea otter + jellies + sloth",
        hunt_finds=["octopus", "shark", "clownfish", "stingray", "seahorse", "starfish"],
        hunt_challenges=[
            ("van_otter", "Sea otter: snack on the belly or a back float?"),
            ("van_jelly", "Moon jelly: watch one pulse from top to bottom."),
            ("van_sloth", "Tropics sloth: mid-reach or statue-still?"),
            ("van_octo", "Giant Pacific octopus: how long until you spot an arm?"),
        ],
        display_names={
            "sea-otter": "Vancouver sea otter",
            "jellyfish": "Vancouver jelly",
            "two-toed-sloth": "Tropics sloth",
            "octopus": "BC Coast octopus",
            "shark": "Vancouver shark",
            "clownfish": "Tropics clownfish",
            "stingray": "Reticulate whipray",
            "seahorse": "Barbour's seahorse",
            "starfish": "Wet Lab sea star",
            "freshwater-fish": "Vancouver freshwater fish",
        },
        treasure=[
            "Watch a northern sea otter float or snack",
            "Slow down at the moon jellies",
            "Hang-and-look-twice at a Tropics sloth",
            "Find a giant Pacific octopus hide",
            "Count shark fins",
            "Find a clown anemonefish",
            "Pick a Vancouver Aquarium favorite — draw it later",
        ],
    )

    apply_kit(
        "virginia-aquarium",
        verified=False,
        tagline="Starter list: sharks, sea turtles, and the Jellies Gallery — otter habitat is vacant.",
        items=[
            item("shark", zone="Restless Planet / exhibits", one="Nurse, sandbar, sand tiger, zebra, and catsharks.", core=True),
            item("sea-turtle", zone="Exhibits", one="Green, Kemp’s, and loggerhead sea turtles.", core=True),
            item("jellyfish", zone="Jellies Gallery", one="Jellies Gallery plus a moon-jelly touch pool.", core=True),
            item("stingray", zone="Exhibits", one="Spotted eagle ray and southern stingray.", core=True),
            item("eel", zone="Exhibits", one="Green moray eel.", core=False),
            item("freshwater-fish", zone="Wetlands", one="Longnose gar and catfish — look for a flash.", core=False),
        ],
        bans=bans_except(set(), [
            ("asian-small-clawed-otter", "Official: Otter Habitat is currently vacant; species never named."),
            ("sea-otter", "Otter habitat vacant; not a sea otter exhibit."),
            ("octopus", "Not named on official animals / building-exhibit pages."),
            ("seahorse", "Not named on official animals / building-exhibit pages."),
            ("clownfish", "Not named on official animals / building-exhibit pages."),
            ("african-penguin", "No penguin on official exhibit pages."),
        ]),
        sources=[
            "https://virginiaaquarium.com/animals",
            "https://virginiaaquarium.com/north-building-exhibits",
            "https://virginiaaquarium.com/south-building-exhibits",
        ],
        notes="[2026-08-23] Wave 4: virginiaaquarium.com featured animals + building exhibits. Otter habitat vacant. Short overlap. No invented verify date.",
        hunt_tag="Virginia bonus · sharks + turtles + jellies",
        hunt_finds=["stingray", "eel", "freshwater_fish"],
        hunt_challenges=[
            ("va_shark", "Sharks: count the fins you can see at once."),
            ("va_turtle", "Sea turtle: flippers busy or a still float?"),
            ("va_jelly", "Jellies Gallery: watch one pulse from top to bottom."),
        ],
        display_names={
            "shark": "Virginia Aquarium shark",
            "sea-turtle": "Virginia Aquarium sea turtle",
            "jellyfish": "Jellies Gallery",
            "stingray": "Virginia Aquarium ray",
            "eel": "Green moray",
            "freshwater-fish": "Wetlands fish",
        },
        treasure=[
            "Find a Virginia Aquarium shark",
            "Spot a sea turtle",
            "Slow down at the Jellies Gallery",
            "Watch a ray glide by",
            "Find a green moray",
            "Pick a Virginia Aquarium favorite — draw it later",
        ],
    )

    apply_kit(
        "waikiki-aquarium",
        verified=True,
        tagline="Seahorses first, then Ocean Drifters jellies and Hunters on the Reef sharks — green sea turtle is not on exhibit.",
        items=[
            item("seahorse", zone="Amazing Adaptations", one="Seahorses in Amazing Adaptations — tail hold-on.", core=True),
            item("jellyfish", zone="Ocean Drifters", one="Ocean Drifters jellies — watch them pulse.", core=True),
            item("shark", zone="Hunters on the Reef", one="Hunters on the Reef sharks (zebra shark on exhibit).", core=True),
            item("octopus", zone="Animal guide", one="Octopus on the official animal guide.", core=True),
            item("cuttlefish", zone="Animal guide", one="Cuttlefish on the official animal guide.", core=True),
            item("starfish", zone="Animal guide", one="Linckia sea star.", core=True),
            item("crab", zone="Animal guide", one="Box, ghost, and hermit crabs.", core=False),
            item("eel", zone="Animal guide", one="Eels on the official animal guide.", core=False),
            item("stingray", zone="Sharks and rays", one="Freshwater stingray in the sharks-and-rays guide.", core=False),
        ],
        bans=bans_except(set(), [
            ("sea-turtle", "Official animal guide: green sea turtle is not on exhibit."),
            ("clownfish", "Damselfish pages are sergeants, not clownfish."),
            ("asian-small-clawed-otter", "Not on the official animal guide."),
            ("freshwater-fish", "Not used — freshwater stingray maps to stingray, not this card."),
            ("african-penguin", "No penguin on the official animal guide."),
        ]),
        sources=[
            "https://www.waikikiaquarium.org/experience/exhibits/",
            "https://www.waikikiaquarium.org/experience/animal-guide/",
            "https://www.waikikiaquarium.org/experience/exhibits/amazing-adaptations/",
            "https://www.waikikiaquarium.org/experience/exhibits/ocean-drifters/",
            "https://www.waikikiaquarium.org/experience/exhibits/hunters-on-the-reef/",
        ],
        notes="[2026-08-23] Official-source Wave 4 public list pass (waikikiaquarium.org exhibits + animal guide). Green sea turtle marked not on exhibit.",
        hunt_tag="Waikiki bonus · seahorses + Ocean Drifters + reef hunters",
        hunt_finds=["octopus", "cuttlefish", "starfish", "crab", "eel", "stingray"],
        hunt_challenges=[
            ("wai_horse", "Seahorse: tail wrapped or swimming free?"),
            ("wai_jelly", "Ocean Drifters: watch one pulse from top to bottom."),
            ("wai_shark", "Hunters on the Reef: count the fins you can see at once."),
            ("wai_cuttle", "Cuttlefish: which color did it try first?"),
        ],
        display_names={
            "seahorse": "Amazing Adaptations seahorse",
            "jellyfish": "Ocean Drifters jelly",
            "shark": "Hunters on the Reef shark",
            "octopus": "Waikiki octopus",
            "cuttlefish": "Waikiki cuttlefish",
            "starfish": "Linckia sea star",
            "crab": "Waikiki crab",
            "eel": "Waikiki eel",
            "stingray": "Waikiki stingray",
        },
        treasure=[
            "Find a seahorse in Amazing Adaptations",
            "Slow down at Ocean Drifters",
            "Count Hunters on the Reef fins",
            "Find an octopus hide",
            "Find a cuttlefish disguise",
            "Spot a Linckia sea star",
            "Pick a Waikiki Aquarium favorite — draw it later",
        ],
    )


if __name__ == "__main__":
    main()
